### ISSUE TITLE
代码支持非英伟达显卡的电脑运行吗？

### ISSUE THREAD

**Issue by z0x0x0** [jiwei0921/CoNet#2]
您好，我是一名对显著性检测感兴趣的小菜鸟，作为自学python小白，希望您可以帮助我，因为安装pytorch时安装的是only cpu 版本（电脑无英伟达显卡，是inter uhd 620），就担心是不是对跑代码有影响，因为pytorch里的package反复报错，

Traceback (most recent call last):
  File "demo.py", line 136, in <module>
    training.train()
  File "C:\Users\conet\trainer.py", line 169, in train
    self.train_epoch()
  File "C:\Users\conet\trainer.py", line 60, in train_epoch
    for batch_idx, (data, target, depth, edge) in enumerate(self.train_loader):
  File "C:\Users\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "C:\Users\12874\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1148, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\anaconda3\envs\pytorch\lib\multiprocessing\queues.py", line 104, in get
    if not self._poll(timeout):
  File "C:\Users\12874\anaconda3\envs\pytorch\lib\multiprocessing\connection.py", line 257, in poll
    return self._poll(timeout)
  File "C:\Users\anaconda3\envs\pytorch\lib\multiprocessing\connection.py", line 330, in _poll
    return bool(wait([self], timeout))
  File "C:\Users\anaconda3\envs\pytorch\lib\multiprocessing\connection.py", line 859, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Users\anaconda3\envs\pytorch\lib\multiprocessing\connection.py", line 791, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)

**Comment by jiwei0921** [comment]
Thanks for your interests in our work. I have replied in your email.
